# Generated by Django 5.2.5 on 2025-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.CharField(max_length=5000)),
                ('createdby', models.CharField(max_length=100)),
                ('modifiedby', models.CharField(max_length=100)),
            ],
        ),
    ]
