# Generated by Django 5.2.5 on 2025-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
