# Generated by Django 5.2.5 on 2025-09-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_quotes_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='createdby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='modifiedby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
