# Generated by Django 5.2.5 on 2025-09-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_quotes_author_alter_quotes_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='active',
            field=models.IntegerField(),
        ),
    ]
