# Generated by Django 5.2.5 on 2025-09-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_quotes_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='quotes',
            new_name='quotes_a',
        ),
    ]
