# Generated by Django 5.2.5 on 2025-09-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_quotes_quotes_quotes_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='createdby',
            new_name='createdat',
        ),
        migrations.RenameField(
            model_name='quotes',
            old_name='modifiedby',
            new_name='modifiedat',
        ),
    ]
