# Generated by Django 5.2.5 on 2025-09-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_createdby_quotes_createdat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sabhasad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('division', models.CharField(max_length=100)),
                ('contact_no', models.BigIntegerField()),
                ('reg_date', models.DateField()),
                ('dob', models.DateField()),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('createdat', models.CharField(blank=True, max_length=100, null=True)),
                ('modifiedat', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
