# Generated by Django 5.2.5 on 2025-09-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_sabhasad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabhasad',
            name='active',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
