# Generated by Django 5.2.5 on 2025-10-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_admin_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_reg',
            name='createdat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_reg',
            name='modifiedat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_reg',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
