# Generated by Django 5.2.5 on 2025-10-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_admin_reg_createdat_admin_reg_modifiedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_reg',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
