# Generated by Django 5.2.7 on 2025-10-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_admin_reg_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_reg',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
